
```{r, warning = FALSE }
# remove  all objects from the environment (optional)
rm(list=ls())
# set the working directory to the project root
library(this.path)

current_file_path <- this.path::this.path()
current_dir_path <- dirname(current_file_path) # scr
project_dir_path <- dirname(current_dir_path) 

```

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir =project_dir_path)
setwd(project_dir_path)
getwd()
```



```{r}
library(Seurat)
library(dplyr)
library(ggplot2)
library(reshape2)

# CD to the miic folder
#R CMD INSTALL --library=/Users/alichemkhi/Desktop/code/miic_lib_210 ./
#library(miic ,lib.loc="/Users/alichemkhi/Desktop/code/miic_lib_210") 
#library(miic ,lib.loc="/Users/alichemkhi/Desktop/code/miic") 
library(miic)
# check miic version
packageVersion("miic")



dataset.path<-"/Users/alichemkhi/Desktop/myProjects/2D_gast/output/v0.2/dataset.filtered.grouped.rds"

dataset.so    <- readRDS(file =dataset.path)


# subset the celltype_grouped
dataset.filtered.so <- subset(dataset.so, subset = celltype_grouped %in% c("aPS"))
# subset the condition 
dataset.filtered.so <- subset(dataset.filtered.so, subset = condition=="WNT")
# subset timepoint
dataset.filtered.so <- subset(dataset.filtered.so, subset = time %in% c("t36","t37"))

# check matrix dimensions
dim(dataset.filtered.so@assays$RNA$counts)

matrix_ <- Matrix::t(dataset.filtered.so@assays$RNA$counts)

mi_scores <- miic::selectFeatures(
    matrix_,
    n_features = 0,
    var_of_interest_values = NULL,
    var_of_interest_names = c("T"),
    n_threads = 8,
    corrected=FALSE,
    unit="bits",
    verbose = 3,
    plot = FALSE)

# get rows with name "CTBP1"
mi_scores$mi[rownames(mi_scores$mis) == "CTBP1", ]
mi_scores



mi_scores_2 <- miic:::compute_mi_batch(
    matrix_,
    var_of_interest_values = NULL,
    var_of_interest_names = c("T"),
    n_threads = 8,
    corrected=FALSE,
    verbose = 3)

mi_scores_2[rownames(mi_scores$mis) == "CTBP1", ]

matrix_[1:5,1:5]
```

```{r}
T<-matrix_[,"T"]
CTBP1<-matrix_[,"CTBP1"]
miic::computeMutualInfo(T, CTBP1,plot = FALSE)
# 

```

```{r}
dataset.so@meta.data
# https://miic.curie.fr/job_results.php?id=BtaXTxayNcYdLBw5rAIy (WNT)


#/Users/alichemkhi/Desktop/myProjects/2D_gast/output/v0.5/single_gene_plots_['ExeMes']_['aPS']/T_mi_scatter_colored_unfiltered.html
```


#---

```{r}
library(Seurat)
library(dplyr)
library(ggplot2)
library(reshape2)

# CD to the miic folder
#R CMD INSTALL --library=/Users/alichemkhi/Desktop/code/miic_lib_210 ./
#library(miic ,lib.loc="/Users/alichemkhi/Desktop/code/miic_lib_210") 
#library(miic ,lib.loc="/Users/alichemkhi/Desktop/code/miic") 
library(miic)
# check miic version
packageVersion("miic")


# Read matrix and metadata
#   --matrix  /Users/alichemkhi/Desktop/myProjects/miic_helper/data/wnt_data_counts.csv \
#   --metadata /Users/alichemkhi/Desktop/myProjects/miic_helper/data/wnt_data_metadata.csv \
matrix_df <- read.csv("/tmp/filtered_matrix.csv",check.names = FALSE, row.names = 1)
meta_df   <- read.csv("/tmp/var_of_interest_values.csv",check.names = FALSE, row.names = 1)

colnames(matrix_df)

var_of_interest_values <- meta_df#[, c("condition"), drop = FALSE]

# Run MIIC
mi_scores <- miic:::compute_mi_batch(
  matrix_df,
  var_of_interest_values = var_of_interest_values,
  var_of_interest_names = colnames(matrix_df),
  n_threads = 6,
  unit="bits",
  corrected=FALSE
)


#mi_scores

```

